#!/bin/sh

config_dir="$HOME/.config/synergyw"
synergy_config_dir="$config_dir/synergy"

USAGE="USAGE: $0 [-s] [-e] CONFIG"

die() {
    status=$1
    shift
    warn $@
    exit $status
}

warn() {
    echo $@ >&2
}

mk_private_dir() {
    test -d "$1" || mkdir -p "$1" && chmod 700 "$1"
}

get_program() {
    prog=$1
    which_program="$(which $prog 2>/dev/null)"
    win_program="$(ls /cygdrive/c/Program\ Files*/Synergy/$prog.exe 2>/dev/null)"
    prog="${which_program:-"$win_program"}"
}

hash_it() {
    hashed="$(printf '%s' "$password" | md5sum | sed 's/[^a-f0-9]*//g')"
    crypt="--crypto-pass $hashed"
}

client() {
    get_program synergyc
    test -n "$password" && hash_it
    "$prog" --debug DEBUG $crypt $hostess
}

get_config() {
    test $# -eq 1 || die 1 "$USAGE"
    config="$config_dir/$1"
    test -f "$config" || die 2 "$USAGE\n$config is not a file"
    . "$config"
}

server() {
    get_program synergys
    synergy_config="$synergy_config_dir/$synergy_config"
    test -f "$synergy_config" || die 4 "$0: in $config: $synergy_config is not a file"
    "$prog" -c "$synergy_config"
}

list_files() {
    echo "Files in $config_dir:"
    find "$config_dir/" -maxdepth 1 -type f 
    return $?
}

edit() {
    edit="${VISUAL:-$EDITOR}"
    edit="${edit:-vi}"
    $edit "$config"
    synergy_config="$synergy_config_dir/$synergy_config"
    test -f "$synergy_config" && $edit "$synergy_config"
}

show() {
    echo "showing $config:"
    cat "$config"
    synergy_config="$synergy_config_dir/$synergy_config"
    test -f "$synergy_config" || return
    echo "-----------"
    echo "showing $synergy_config:"
    cat "$synergy_config"
}

mk_private_dir "$config_dir"
mk_private_dir "$synergy_config_dir"

while [ $# -gt 0 ]; do
    case "$1" in
      -l)
        list_files
        exit $?
        ;;
      -e)
        action="edit"
        shift
        ;;
      -s)
        action="show"
        shift
        ;;
      --)
        shift
        break
        ;;
      -*)
        die 1 "$USAGE: flag $1 not recognized"
        break
        ;;
      *)
        break
        ;;
    esac
done

get_config "$1"
action="${action:-"$role"}"

[ "$action" = "client" ] || [ "$action" = "server" ] || \
  [ "$action" = "show" ] || [ "$action" = "edit"   ] || \
  die 3 "$0: in $config: role should be 'server' or 'client', not '$role'"

$action
